name: composer

on:
  push:
  pull_request:
  
jobs:
  composer:
    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3', '8.2' ]
        dependency-version: [ 'prefer-lowest', 'prefer-stable' ]
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, json
          coverage: none
      - run: composer validate --strict
      - run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress --no-interaction --no-suggest
