name: pest

on:
  push:

jobs:
  pest:
    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3', '8.2' ]
        dependency-version: [ 'prefer-lowest', 'prefer-stable' ]

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, json
          coverage: none
      - run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress --no-interaction --no-suggest
      - run: vendor/bin/pest

  type-coverage:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.2
          extensions: curl, json
          coverage: none
      - run: composer update --prefer-dist --no-progress --no-interaction --no-suggest
      - run: vendor/bin/pest --type-coverage
