name: phpstan

on:
  push:
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: curl, json
          coverage: none
      - run: composer install --prefer-dist --no-progress --no-interaction --no-suggest
      - run: vendor/bin/phpstan --memory-limit=2G
